image: gradle:4.10.2

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
  - .m2/repository/
  - target/

stages:
- build
- publish
- release

build:
  stage: build
  script:
  - gradle clean check

publish_snapshot:
  stage: publish
  script:
  - gradle release
  environment:
    name: publish_snapshot
  only:
  - master

publish_release:
  stage: publish
  script:
  - gradlew release

  environment:
    name: publish_release
  when: manual
  only:
  - /release/.*$/
