language: java
jdk:
- openjdk8
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build pull request
    script: "./gradlew spotlessCheck check jacocoTestReport"
    if: type = pull_request
  - stage: build master
    script: "./gradlew spotlessCheck check jacocoTestReport uploadArchives"
    if: branch = master AND NOT type = pull_request
  - stage: build and stage release
    if: branch =~ /release/
    script: "./gradlew check uploadArchives -Pversion=${TRAVIS_BRANCH#'release/'}"
  - stage: build and stage release
    if: branch =~ /release/
    script: "./gradlew closeAndReleaseRepository"
  - stage: github release
    if: branch =~ /release/
    script: "./gradlew check -Pversion=${TRAVIS_BRANCH#'release/'} && ./scripts/github-release.sh"
  - stage: release dependants
    if: branch =~ /release/
    script:
    - "./scripts/release-dependant.sh web3j-quorum"
    - "./scripts/release-dependant.sh web3j-cli"
    - "./scripts/release-dependant.sh web3j-gradle-plugin"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- |
  if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_661235106ac6_key -iv $encrypted_661235106ac6_iv -in web3j.asc.enc -out web3j.asc -d
  fi
env:
  global:
  - secure: vui6wYzHWgaruybt04rl+igGuk66EWb+xpaBPflqgN/39zIsue+XTVkq7pS3Fa11salpJztoGeAuFZXDqGwzAA0U401eh7dero84cOLOSyYIX5cwA5RuS+6R/+dC0iJRDFs3Uod33g8oLAEiUXLuChOy1AMrBj/uqZb5Ovmb3QKDSg5MZ/1/bnckFAvYSQqdTLSHzi3bj1jttA0fovs/yNa9D+7BoS1G1r7kO1p4AaRvUfqdcqlf7nqKWrlthkkFqr3DKBz3fHfzjhRuCY45RkGrV9OgGxtpVygHk8o6EsW24q+EGdh8IyqHJuUEpz5txgEDoZQcRbyp+bQsriQ7NyAQsOUaFzJ/xn904DyKDmOWq8bOcbmpIMHXfMYPpdlUXoyQSdZ7WK/Z6jCBm8qgNR3rQauijlSPDCr/UecW4wFbuRSKER0Tf09XpnNfYF/ogBuUhgwOIFet0n+w01FFBXP0MFOUIJrQQKAn6OxqUnzR8jsPDiXW9hZQl1/rmCXISgJ6jdKecw9boJ+nkYRjWjnkL3PqD4JI70oLVAYerabP92aGWcUrhwD+sf1oUMFwAXyqkGQUZnWHYVgaMztXGEv7WLlSrH16FJY2GXt1oPgXDEn+bE4yduMqI9e8c12cvqQWHEb2ohQTaHKGzI0Izau84D5Ine8ZxBM7aN8hWlc=
  - secure: Y0m31w0UsZqWC+bN9q5uKfDeukrl2F8dfODQ36ThKnNCG1N9tKWEeSsX6nDPYQUzrwwIe97r8EpW7BpeFLAie0txzASOvmhGuL25TQPPv99+VMogVcySe0SzOHwxxeCLsxORRzOJPD34XuZptLoN621MX3RdJ/3goy7taE7S4X+ouu1jp06jwxwa0kguLXARjZNVMdcI5hUNIwTfo2gbC3hlXCXwFuA+a+CNQIndtgScEwx16DYz/e+zZEHMKvCPTevZOUigOL09SHK/ehqtMeOigfvVptM2LHqyxz5tRI4M0kgE46eKZPFmiN8PkgN0obB09zGQP1vci1jZg+vElaBq0VY6GKSknUpLjP5nMU+cnSSVvLA7ZilTWPRVVXJxOAETiq95Zo3pDHECUazlSkv8qmXVklT71qCH/grGL/z6vdXPjg+mX921UUtcY0Q+uqc6AXPt6+u5nd2oi66RJg4n9cZyme6WzWShO6ZPuPO+67zXLEvm9DB3OyNQbznfdsBxoLXZmktcj69eNox9dbVmL5ihSwPxQLd7baaI+TcduvzX/RcMNd1XIdJ5NbSlWYGNuj/JBxgCBjt5CIrh/VJS9+5KO8p0XbU9yQXFBvjCFkg/8rH/MozOstx4ldxPNBP6fsyLMqobfyp/L++vFOgeH9yBwdwuPG8ZHvbNckQ=
  - secure: mgM908Mtc3SgUpV5dAdf/ClUTWQXh6Akr5tqwbzlm1rScYaVBvMjO5bX0jPT32rQ0AsxRfirE9bw4b0IMHVJWLlg3TmA37htqKITPlNZ4sAOkHmsNtvpQW9neBJl9zHJCAzPD+4puBEcQYmJqBm+5Hz2tS9MmCLnOqi2omI9BnOSCzb60iccpqv/WnW/kdAlgNlzGCXhbeslsYM89deJznRrjWSAmcC7H0qMrEsR/8paPp6NaslHAaPsirEGCfk3uScbT/NmwBLv5z11DWxuWAfd00oc2SAdCb736VlWdnb4EPG60l53dzQ7Zwn3PuZqD6c1MiKPQ3LYlsZ5Whs9QRhqyEiPb/DAfpQM26E81GExrm0X7JLwWZ79uS0S/38999He+yaOoFLx5jfpRkhutpzEsKI6Tf3tGcUrif9A60J6MtH8y1PChronps10tPXnclX7X+oh5osY/TGurvjgbKRLKEo6uKn4XCWFuVtg7iUuQSbsGQwjrvIFkly/CoEc9jYHH5JFY5b096UUYNCMpOphAqGJubO2aqc/E1aYY1RmGf0soA9TxBsTrXM7ExcJudshdSAU3Uek+LtB6plFYDe1GryV3nHUTtKDxcqJpMywIBIthiLMwbV72vwIVQgn+mjLQK907lgqKbj6Vi7SuosmktPT6hJ2WUKu74fTCGg=
  - secure: AwW7+6ij8g117VDBAtNh+FzMjbIN/xlMEoTnzVlign+Ywg3HbGonxp5HYpVAB48dhu3vU1KrVvokMnAJzFn2ZeXoUDyMoiuKRhXF5yOibgAdpHSpVFuctQTPvbGajbviX9LUxbFprh7JAXyAtFSPqTOakZPUbCEwUC0T3ShTz3qjn57dXDy/734seG2SZ7Jen8ojgj4EqulnHN6UZdhM0wv519kLeJ3kHlSf8gAr785t2OZBrO3b2Wf5zuMjsNET4rkcc4y4cnKOTzCn23RcSEwEctsZPtuwpaOt3MOnSxACGLTHgsyZNv9j2uuUKagnu+h/R3wwy1+DvJSP2Cq3x+Dmdx6lpPx38CmGxzNDuO8wV0n9VljHMq6WQU8cIkH4cnBjqOqld8+j6vOF2rdrmfak3Wn2snYCWIp7com9EafFclYNmssve6DM43uO9G+gyyAmB0KSir4ZhR/l1x3C8B8ScIPUM36h8DGjZ185+PVKRbg/pr7jDQb9C0j8za4BVWJv2BAvI9sWCp4wHWFctZwNyhs7fs733Xk8BNaaUECDf3mKGNfMFtVw1LjRb7jNVmVX/XVl2kbWN8w8hGA079PrdSPs2K6Zq5c7FQZjlk1LtOpXCk44zMqyUKscNhPWKgL5dZVaR+R7K0ZWBK5jntramqNqdsPixabVOxLqJ3g=
