language: java
jdk:
- openjdk8
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build pull request
    script: "./gradlew spotlessCheck check jacocoTestReport"
    if: type = pull_request
  - stage: build master
    script: "./gradlew spotlessCheck check jacocoTestReport uploadArchives"
    if: branch = master AND NOT type = pull_request
  - stage: build and stage release
    if: branch =~ /release/
    script: "./gradlew check uploadArchives -Pversion=${TRAVIS_BRANCH#'release/'}"
  - stage: build and stage release
    if: branch =~ /release/
    script: "./gradlew closeAndReleaseRepository"
  - stage: github release
    if: branch =~ /release/
    script: "./gradlew check -Pversion=${TRAVIS_BRANCH#'release/'} && ./scripts/github-release.sh"
  - stage: release dependants
    if: branch =~ /release/
    script:
    - "./scripts/release-dependant.sh web3j-quorum"
    - "./scripts/release-dependant.sh web3j-cli"
    - "./scripts/release-dependant.sh web3j-gradle-plugin"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- |
  if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_661235106ac6_key -iv $encrypted_661235106ac6_iv -in web3j.asc.enc -out web3j.asc -d
  fi
env:
  global:
  - secure: oMOM2rf/lwsyFUz7Dx8h7AyK5kutf2ivLvc1rfhI9BkWPeUYv4Mfpbcu73lkHviZHOiPW5wIP9C7Runv4lNF3BECjXwcjpOlh3wB/4TczYSWhy3AAwVNjmmp+baJYIs5nmb+I/tH3K+8twHi/Eny69Si26l453MwjWJIMUndw0Ieiq1erafs6GNax8sw7ko1bne5aZjM81vsIaVLg/HJIHt7znz0OjxdCE88/w9UXUP0WVU7czAXRjL85u98YedIz+W3RVrhDbIrhwfzWt9NHOOLDOogsHfHB3NEcXHyylaGO4er2Myp2m31ZPuqxYHkLgETT92gVumt11YEwxRssRyI13tD2vtG9mF6xMZ8yUthL1IfUGNaQJgWfqLstDS/mf5OkByNKvBfjyltQq/T+KXCR9qnbdtkOxfBYsSYzCkmvoqoJjppT4C95KR9U79vQrBbofMmh6I/iNzrpS2KOeq2DKaIHOEi2/iUGS4I/fvDmH4h2hYOzOdhHfzHztUXzdIhLl/QEjOLsOIPeT7qR2n7MSaa4cwRzO8fiKNit/FCc16xHWEDaKcZ1LSHABiBKC3vu2HoaeYv7dlFSoKA9qB+TVJ6eG8tsXDDRNfn8RtU/jiJ531bNqW55ItjZbs3H27yfpnGgeA0x93DVCpHLQtSz1o28+Yrq8Q0yzam31Q=
  - secure: VN2erDgu1+V+mCH/nVJLlhrYdQ1TXXl7CHauNl/fdo1I3jGjxV0lMM7vwTRNUQ+9fr81qiVnA6gfoscbxEifH+wMMHIv4dEYGBy565kdTHMuM41X10HKtoiPdFTFJKKhc2rhAxT2FXqnL5ytmMZhpdmj3/6WjhGudiH9it8OcN/0I5E2bSvDng7Dw71du2BWP1CIwXm1ytPkoqPVfNa5NSoHUvPKKlRzlexARvQjxR4/efNLECzM+PDo3IaH7/JCrnCMyz2u0veKckwbXZSL8lQHl4wIGr2DTRxpfLAKOtcWEjP+kMcllcot3M16THyXZdtCb1uEx0GqcMgz0gzxxTXv0qfmAJkjImMim1Vr2T1DCgv9uPSGho8Ub+Mh9B1FbR7ZPtoPHSLLfbMKmCiHuBh62oyybdJfiimdc9d0un24gpKNtFEsYOnct9hAD/V/bEH3Si9MQ+5qVZAi6YixBPf5rCv1pzhX1SRau2dqk0ebcHCuk8FfW8FQRPc1Q5Dfb2va2a2YqUoeC6dHtWwHiuvv2lP0fBqlr1fU9MXl2+zBhWbxGPFiql/WWBuB7f7ypb56VCmdAW7CtLjWnEKND2RgIt20fRQ2wjF3E0nmHg6sh8RlAlMLm+mEIQqOJavhF1O3OJUJ01yurpJHKw0e168qvQ/wxGGcp7RhTbH3uBM=
  - secure: UaMrNgxDqk9ooDgEScypnGdeuuOfTA1hPUA/bK7kcB7yk0QKFysSZ7JdqDZNTgNXdQKOrPIRGnj3dmHu3cJn8ToVjEQ4522+QtRX0YX7GIkQo2OLzw9DX7MoulYN7ddD3gCdea4AHo15fgMLxTeBNArvOa0Gxg6goKin2E9Ojc5XcvnpVR0vMiv/WKWejiuXkMXKDqEC4rSSTu/1wBi7PY/Z2oeLhV3szQeOWzjV4T0GrjKw+X2xEZhx9PGaql4EIAPUFu2Q3Dtl/nmjEMXKTRk0aAx8/p/rUG21s2X94aoI5c2+kPw7g/Xu/RY4YT9KwegzKbooYC8VKZrGqFHpW+2zYDjSkDFE/Aqy0lQKAhgSo1vwQulBB32KNFXNLjiXAnCV31t9+Ecq/Oua++8jgRDsIR+W3z5jFGSIYdTrCWA8uwJbaof9qnGZ2xByE90nFm5W/d9TwmQnJjKIlL/2W+8s8No4oN/QWUxSBcLeEPyx7kr7sIxbIrsb+q8aXOrGKUgRZvrX38H6Is+ToFKL9PBK454H5EycMybsxGsz60tkSH7whPE/4wkbv5Y0S9pqJswEu59WRUYRkNWR2vtCV4QaAqpMbZ1YvTK4Wy/tPuAVozsg62v4XfG2RgUUqLNPhAPXZHNLgK9HbVO486FXxAeRQEI680NwsK0+DnZGyrc=
  - secure: ewtJTdDDETA3007pQUVSrfJmkbuVHfSRy9thLCUL08pH1MwzpKDCTSKTu7BPLetzO3GFGV6eIsh8zKwDkH/mPHaHnzJU4tIhYN7S57y/THZjxjuBjDGAfuAf7rw0nfxRkCi19eun3oAZNtJuY6IxYjH8YeQUPk/jMlkycOaTihdBUPeTPv+C4WyTKyj5/3AiOxSqpMLg7CkHMLTrdIO7BARBtjjsH3UJ2od5oB2nEO8UrUa1fcGAEvvjoiivu8/lFdsDOcc6gbXEGf9ve00vU7bsxuk5/B3p74O4qUC1rT+bj2l3m7SCBl73f50dbUoTeguy4ciRkLihKc+5eGGM8kgsIZZQfEXaZkxD3zg4s78WGMw2ah4V6QapHUgsg0NKo4I+5DBRuKxNjZBzLyzAzmLCqfHd5X83jXMLdm/V2F2f98HQDQ7MwWjWA6U1sI1UjFSaSyv/JR5CHWg3/2olp+Oalsg0VWk5aSSi6xdi6DIDwUApzCKyw/NPbwFTSowxcD1g9GOclTnJ3VUE+WrBfkfVHg4/NZCWTe95JT6tM5s107XYyNgym1WJfjTR9juogS167Rg5MHS3Lwc6W68V7mtELL0FPcqAvmXaR6bn2boM1OnaDfqksw1Kqb+gzDKyUWUmE2peij3whP8DzrHhbRusmqarjtgpAREYQJlujxM=
