language: java
jdk:
- openjdk8
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build pull request
    script: "./gradlew spotlessCheck check jacocoTestReport"
    if: type = pull_request
  - stage: build master
    script: "./gradlew spotlessCheck check jacocoTestReport uploadArchives"
    if: branch = master AND NOT type = pull_request
  - stage: build and stage release
    if: branch =~ /release/
    script: "./gradlew check uploadArchives -Pversion=${TRAVIS_BRANCH#'release/'}"
  - stage: build and stage release
    if: branch =~ /release/
    script: "./gradlew closeAndReleaseRepository"
  - stage: github release
    if: branch =~ /release/
    script: "./gradlew check -Pversion=${TRAVIS_BRANCH#'release/'} && ./scripts/github-release.sh"
  - stage: release dependants
    if: branch =~ /release/
    script:
    - "./scripts/release-dependant.sh web3j-quorum"
    - "./scripts/release-dependant.sh web3j-cli"
    - "./scripts/release-dependant.sh web3j-gradle-plugin"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: bDdxx2/4NbmV/we/GeFkV7SSmy/18cYpegU8MFaxmizrcSjsXQaadAooMVd0eGAcf15m3pOmJ6n7pqv0I8hs5SWN2L5hb1StJVqR0f+SeoEdf5vprxoGRF1Q6VgKWSNP9FQoABWhQHzXF2NMY3bZcEN5+6kOeZ11qSPHXMWKRg3Utc5tS5Ck7XazGrNe1b99zWt0FPJaKnNYnQ6ClL2YYZ1Jlm7243aWLhnBzA2hX+v7c8EiK/lawTNDdPmN9qbYrtopTbGso0Elc4aD8dk2yROK1WKETzctkvn/cW/OZ0ipN3TTEp72VAKhbc+1M4DvY4QyhHZUc34bwd/1evlgUD6D1gf61z9kkmFiyEDyEmOdhvHoYppMkJlmu3h4sYp8r2R1GMPoQOVFGlbjtXrKY/SZcDzxqz6/hwK0BFJL7oDgcemmBzfFVdnhPYuwrje15LhTtdBQ0n5soEaje3cKtjE2GGb59gCKepqwbShn7ne2rcUuqiub+8Qa1T/yDgfa6YBOVp1R5Dfp/r9Z3m3s3frH/C01ACul/We4iZQsWFCViD6+MGag/op7Zs1B6Ueb4RyzlSQ819VMxWDdFZQag5mQD9jz2+4huCRC4KAvl4aRJZcVc6RjuUkQeBn9z6skW6Db3jMctud5CSYbdvIPxtdDKNlkcRWF+S83Hos/r28=
  - secure: sIn3Li0ug1SgXe8ZMdSkZASlT8lL029+k6YNUsLLBFSy8/2yWsVewGu+uDQSgzhIk6oK4m6sndD6E4UCCAOVaA0ObTLbSsbXISooeBGdX4zXt146ZKRfjKPcZLLpW8kedXfzK2WZmjjD7A31WqcHnC+4xEhQSodYveh3Ovl3JA2u00qLde74hwc+AV8Hrvk4OoqWhjqOJv9RRC9KUUHi5f1ta39Tz4ioSbHsdkNph343niGMecYERsdqj9DTRe30ZfqFSWtzCcciVaLvZih7JpxaZz/FJINcfeZTdCbaA89I8w5HoqU44A6L0ukok8sflHiRYnXpue1Q57KB+TzxIVNbNCdlgdT/9UzXKtjjKmiTdHl/r6EsliNW/c6iLkc08hXJvdLlLS19Dka5AXjAY5GYTyFY0u0I4S4qM3jnAKYWlWV9WLhAfmIXPfL7Yy6W6Cgh5lYVlStHoLHTsZNdNSOyvqKXBcQErgDhYuYqaJN9zlahc+fM1AXieXX/QPbzphx4jIKL+rnPJASP5jzBVIgf7PEanCBtoDHfkVbWtIcx4mA3UZwDrIUsMuUq34JMNNTbkUirdS2GElkq86Ap9mn5ng5uKuyCdgmidjPj7wJ11ovDDWj1gOahINpzle1gu8x8iJV0cxiB+aobqt/wTbzq90XWnFd9U4N5vs1xl84=
  - secure: L9H5TuvCjRldkMYELMc3XcU9okgCBLYJWzdB6oxWLUEhdcAkFGRIVGXKP70WQSuJrPOFegantYsr7QDMErUHfNcg+MnKwQ/Rsq4OBE817KompEQLTuK4i8lkl7rE4TQUfPJN5Xq39W9uYS0VHWG2VX6oRDjefqylDV2lbWk5dtUfvH22nbYJ5yor2lxyqI0VOXf3WXoVb0VJ/YuQkRp91e8nzaYGheMnhEIR+MXSFG1qgoXv3swSzb4wPu9Xpq/idub+qf/DJ2K/S16+EBbZVmwMfYEBM26vJbVgxdb7giC1de9xFTAK/Qs05L74uRpd/gJJqYXPwgQ36LevSGLkBuRlxoceaeGCsvPfb576rsLQaAZWSWiTL/ziE9HiBXoXNJn0CqS93DbobX3YzaR8QlC1Ya04FR5LJl2yyxDD74/xrdG00EduUUL3arR4p2q7FhuVUoJ7UHPonYfOjNazV1+jmDpBg68J7HQo8K5guq0HXwt1PGdpQGcL9Ieq9GYyXNZHypy/cJlE95Fo3RdhjtiIADQ3qIcOhLAOHeHqW3lmS494tTbzP1VDqQUy8kKWAVqCSjV/AmcrwRNCWocVpW5yHUsYsApeeY429UrDVFK1cXKgpkGnXP52fXesqG3bvzP/tvOgPnNpvl0YU6DZGWe+iIVOgqA1d/EQRu9ZgJw=
  - secure: B79RAZpaRpzYibc442tEkr4YTPFTh10zpepNaYf5NI684TfdcO+hrK9wfXHJdGGIWZAn/4IdzjW3ShLR3aZhzXSJ1BrfTTQRvxfUbU6P3UxZyvOzu4tmYOuwwDsqVbJ+FuZ3zh20pSj0qXddOZWwFH2X55sW/KK7L7h62JnofP44V/0MGGl53UBUy4/DFJBjYWSKrDyvbxR2JiE6gwLKB4yBEP5+ykKYGrjwnR88e66el0HNVCoa0Glhm53nYQGVKYSefewvAIC3IwKbtdwxq1bbJxCCvkSsUYPjhT0JVj8oH0WF1ykRSGt/77Hb5h4X7RFlnhtloBCiKUkare0PhXJ1UMePoCHOaDdreX+WjPcUngvZ7qkG7jDoi4LyTjpZf2MJgDgEcV/UUe7wZG/e2r+mNBwKQq7GTpZI44k4yi9BT1JMqOJ/29FdOIYZKYQCDoaBbPHFB1mj6DbfzUqnXohuRHYGoG1WxkTTbyQgeJcpqOtgFTx2bkx4HZbyIM/bAsOz1poJRkc4cNpXT1PSUK9tapQAklSnbGP++q+sZKI4L5x6jU4GwI9O0Sg58lk5VCQolaCKT2KmUedqt8UFnaij/4T535QF/jrRncGPmrHz8ohmhkSUQos8L0Kz6t6j0KSNFRH2mrC71ne7ndi4+lhYJ3s6fVgwjPjm6hA710E=
before_install:
  - |
      if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
       openssl aes-256-cbc -K $encrypted_661235106ac6_key -iv $encrypted_661235106ac6_iv -in web3j.asc.enc -out web3j.asc -d
      fi
